#!/usr/bin/env python3
import json
import os

def load_json(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        return json.load(f)

def save_json(filepath, data):
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

# Generate 100 new Q&A pairs for musik_seni.json
musik_seni_new = [
    {"q": "Apa yang dimaksud dengan tempo dalam musik?", "a": "Tempo adalah kecepatan atau irama dalam musik yang menentukan seberapa cepat atau lambat sebuah lagu dimainkan. Tempo diukur dalam BPM (beats per minute) dan mempengaruhi mood serta energi dari sebuah komposisi musik.", "cot": "Tempo adalah elemen fundamental yang mengatur waktu dan ritme dalam musik."},
    {"q": "Siapa pelukis Indonesia yang terkenal dengan gaya ekspresionisme?", "a": "Affandi adalah pelukis Indonesia yang sangat terkenal dengan gaya ekspresionisme. Teknik melukisnya yang unik menggunakan tangan langsung tanpa kuas menjadikannya salah satu seniman paling ikonik di Indonesia dan diakui secara internasional.", "cot": "Affandi merupakan maestro seni lukis Indonesia dengan karakter kuat dalam karyanya."},
    {"q": "Apa perbedaan antara musik modal dan musik tonal?", "a": "Musik tonal menggunakan sistem nada mayor dan minor dengan pusat tonal yang jelas, sedangkan musik modal menggunakan mode atau skala tertentu yang memberikan warna harmoni berbeda. Musik modal lebih bebas dan sering digunakan dalam musik tradisional, jazz, dan musik kontemporer.", "cot": "Kedua sistem ini memberikan pendekatan harmoni yang berbeda dalam komposisi musik."},
    {"q": "Jelaskan apa itu seni instalasi?", "a": "Seni instalasi adalah karya seni tiga dimensi yang diciptakan untuk mengubah persepsi ruang tertentu. Karya ini melibatkan berbagai medium seperti objek, cahaya, suara, dan video yang diatur dalam ruangan untuk menciptakan pengalaman imersif bagi penonton.", "cot": "Seni instalasi mengintegrasikan ruang sebagai bagian dari karya seni itu sendiri."},
    {"q": "Apa itu chord progression dalam teori musik?", "a": "Chord progression adalah urutan akor yang dimainkan secara berurutan dalam sebuah lagu. Progression yang populer seperti I-IV-V-I atau ii-V-I menciptakan harmoni yang menyenangkan dan membentuk struktur harmonik lagu, memberi arah dan perasaan pada musik.", "cot": "Chord progression adalah fondasi harmoni yang membentuk karakter musik."},
    {"q": "Siapa pelopor seni Pop Art dan apa ciri khasnya?", "a": "Andy Warhol adalah salah satu pelopor utama seni Pop Art. Ciri khas Pop Art adalah penggunaan imagery dari budaya populer dan konsumerisme seperti iklan, komik, dan produk komersial. Karya ikonik Warhol termasuk Campbell's Soup Cans dan potret Marilyn Monroe dengan warna cerah dan repetitif.", "cot": "Pop Art menantang batasan antara seni tinggi dan budaya populer."},
    {"q": "Apa yang dimaksud dengan dynamics dalam musik?", "a": "Dynamics adalah variasi volume atau intensitas suara dalam musik, dari sangat lembut (pianissimo) hingga sangat keras (fortissimo). Dynamics menambah ekspresi emosional dan drama dalam pertunjukan musik, membantu mengkomunikasikan perasaan komposer kepada pendengar.", "cot": "Dynamics adalah alat ekspresi penting untuk menyampaikan emosi dalam musik."},
    {"q": "Jelaskan apa itu seni lukis abstrak ekspresionisme?", "a": "Abstrak ekspresionisme adalah gerakan seni lukis yang menekankan ekspresi emosi spontan melalui gestur, warna, dan bentuk abstrak. Pelukis seperti Jackson Pollock dengan teknik dripping dan Mark Rothko dengan color field painting adalah tokoh utama gerakan ini yang berkembang di Amerika pada 1940-1950an.", "cot": "Gerakan ini membebaskan seniman dari representasi figuratif untuk fokus pada emosi murni."},
    {"q": "Apa itu kontrapung dalam musik klasik?", "a": "Kontrapung (counterpoint) adalah teknik komposisi di mana dua atau lebih melodi independen dimainkan bersamaan namun tetap harmonis. Johann Sebastian Bach adalah maestro kontrapung, dengan karya seperti The Art of Fugue yang menunjukkan keahlian tinggi dalam teknik ini.", "cot": "Kontrapung menciptakan tekstur musik yang kaya dengan interaksi melodi yang kompleks."},
    {"q": "Apa yang dimaksud dengan seni performance art?", "a": "Performance art adalah bentuk seni di mana seniman menggunakan tubuh, suara, dan tindakan mereka sebagai medium artistik. Karya ini sering kali bersifat ephemeral (tidak permanen), konseptual, dan dapat melibatkan audiens. Marina Abramović adalah salah satu performance artist paling terkenal.", "cot": "Performance art menghapus batasan antara seniman, karya, dan penonton."},
    {"q": "Jelaskan apa itu syncopation dalam ritme musik?", "a": "Syncopation adalah teknik ritme di mana aksen atau tekanan ditempatkan pada not atau beat yang biasanya lemah atau off-beat. Ini menciptakan kejutan ritmis dan energi dalam musik, sangat umum dalam jazz, funk, dan musik Latin yang memberi groove dan kompleksitas ritmis.", "cot": "Syncopation menambah dinamika dan interest ritmis dengan melawan ekspektasi ritme normal."},
    {"q": "Apa itu gerakan Bauhaus dalam seni dan desain?", "a": "Bauhaus adalah sekolah seni dan desain revolusioner di Jerman (1919-1933) yang mengintegrasikan seni, kerajinan, dan teknologi. Prinsip 'form follows function' menekankan kesederhanaan, fungsionalitas, dan estetika modern yang mempengaruhi arsitektur, desain grafis, dan seni kontemporer hingga saat ini.", "cot": "Bauhaus mengubah paradigma desain dengan menggabungkan seni dan fungsi praktis."},
    {"q": "Apa perbedaan antara gambar sketsa dan gambar rendering?", "a": "Sketsa adalah gambar cepat dan kasual yang menangkap ide dasar atau komposisi, biasanya dengan garis sederhana. Rendering adalah gambar yang lebih detail dan finished yang menunjukkan cahaya, bayangan, tekstur, dan warna untuk presentasi akhir. Sketsa adalah eksplorasi, rendering adalah eksekusi.", "cot": "Sketsa untuk ideation, rendering untuk presentasi detail."},
    {"q": "Jelaskan apa itu musik chamber dan karakteristiknya?", "a": "Musik chamber adalah musik klasik untuk kelompok kecil musisi (biasanya 2-10 orang) di mana setiap instrumen memainkan part individu. String quartet adalah contoh klasik. Karakteristiknya adalah intimasi, keseimbangan antar instrumen, dan tidak memerlukan konduktor karena musisi berkomunikasi langsung.", "cot": "Chamber music menekankan kolaborasi intim antar musisi dalam ensemble kecil."},
    {"q": "Apa itu seni minimalis dan filosofinya?", "a": "Seni minimalis adalah gerakan yang menekankan kesederhanaan ekstrem dengan mengurangi karya ke elemen paling esensial. Filosofinya adalah 'less is more' - menghilangkan yang tidak perlu untuk fokus pada bentuk, warna, dan ruang murni. Donald Judd dan Carl Andre adalah tokoh minimalis utama.", "cot": "Minimalisme mencari keindahan dalam kesederhanaan dan pengurangan."},
    {"q": "Apa yang dimaksud dengan key signature dalam musik?", "a": "Key signature adalah simbol di awal staff musik yang menunjukkan tangga nada (scale) yang digunakan dalam piece tersebut dengan menandai nada-nada yang di-sharp atau di-flat. Ini membantu musisi memahami tonal center lagu dan menghindari penulisan accidental di setiap bar.", "cot": "Key signature memberikan framework tonal untuk sebuah komposisi musik."},
    {"q": "Jelaskan apa itu seni kinetik?", "a": "Seni kinetik adalah karya seni yang mengandung gerakan atau menciptakan ilusi gerakan. Alexander Calder dengan mobile sculptures-nya adalah pioneer seni kinetik. Gerakan bisa dihasilkan dari angin, motor, atau interaksi penonton, menambah dimensi waktu pada karya seni visual.", "cot": "Seni kinetik menambahkan dimensi waktu dan gerakan pada karya seni statis."},
    {"q": "Apa itu timbre atau warna nada dalam musik?", "a": "Timbre adalah kualitas unik suara yang membedakan satu instrumen dari instrumen lain meskipun memainkan nada dan volume yang sama. Timbre violin berbeda dari flute karena karakteristik overtone dan envelope suara. Ini yang membuat kita bisa mengenali instrumen hanya dari mendengar.", "cot": "Timbre adalah 'fingerprint' auditori yang unik untuk setiap sumber suara."},
    {"q": "Apa yang dimaksud dengan seni land art atau earth art?", "a": "Land art adalah gerakan seni di mana seniman menciptakan karya langsung di lanskap alam menggunakan material alami seperti tanah, batu, dan vegetasi. Karya seperti 'Spiral Jetty' oleh Robert Smithson adalah contoh ikonik. Land art menantang konsep galeri tradisional dan hubungan manusia dengan alam.", "cot": "Land art mengintegrasikan seni dengan lanskap alam dalam skala monumental."},
    {"q": "Jelaskan apa itu ostinato dalam komposisi musik?", "a": "Ostinato adalah motif atau pattern musik yang diulang terus menerus sepanjang komposisi atau bagian dari komposisi. Bisa berupa melodi, ritme, atau bass line yang repetitif. Ostinato menciptakan fondasi dan momentum, sering digunakan dalam musik minimalis dan film score untuk membangun tension.", "cot": "Ostinato menggunakan repetisi untuk menciptakan struktur dan intensitas dalam musik."},
    {"q": "Apa itu seni konseptual dan bagaimana perbedaannya dengan seni tradisional?", "a": "Seni konseptual menekankan ide atau konsep di balik karya lebih penting daripada eksekusi visual atau estetika. Berlawanan dengan seni tradisional yang fokus pada keahlian teknis dan keindahan visual, seni konseptual menantang definisi seni itu sendiri. Marcel Duchamp dengan 'Fountain' adalah pioneer gerakan ini.", "cot": "Konseptual art menggeser fokus dari objek fisik ke ide dan makna."},
    {"q": "Jelaskan apa itu cadence dalam musik?", "a": "Cadence adalah urutan akor yang menandai akhir frase atau bagian musik, seperti tanda baca dalam kalimat. Ada beberapa jenis: authentic cadence (V-I, resolusi kuat), plagal cadence (IV-I, 'amen cadence'), deceptive cadence (V-vi, kejutan), dan half cadence (berakhir di V, tidak terselesaikan). Cadence membentuk struktur dan flow musik.", "cot": "Cadence memberikan punctuation dan closure pada frase musik."},
    {"q": "Apa itu seni kubisme dan siapa tokoh utamanya?", "a": "Kubisme adalah gerakan seni revolusioner yang memecah objek menjadi bentuk-bentuk geometris dan menampilkannya dari berbagai sudut pandang sekaligus. Pablo Picasso dan Georges Braque adalah pelopor kubisme pada awal 1900an. Gerakan ini mengubah representasi ruang dan perspektif dalam seni visual secara fundamental.", "cot": "Kubisme menantang perspektif tradisional dengan multi-viewpoint representation."},
    {"q": "Apa yang dimaksud dengan harmony dalam teori musik?", "a": "Harmony adalah kombinasi simultan dari nada-nada yang berbeda untuk menciptakan akor dan tekstur musik yang lebih kaya. Harmony memberikan depth dan emosi pada melodi. Teori harmony mencakup konsep seperti consonance (akor yang stabil), dissonance (akor yang tegang), dan voice leading (perpindahan antar akor).", "cot": "Harmony adalah fondasi vertikal musik yang menambah dimensi emosional."},
    {"q": "Jelaskan apa itu seni surealis dan filosofinya?", "a": "Seni surealis adalah gerakan yang mengeksplorasi alam bawah sadar, mimpi, dan irrasionalitas dengan menciptakan imagery yang aneh dan tidak logis. Dipengaruhi oleh psikoanalisis Freud, seniman seperti Salvador Dalí dan René Magritte menciptakan dunia visual yang mempertanyakan realitas. Surealis menggabungkan elemen real dengan cara yang tidak mungkin.", "cot": "Surealis mengeksplorasi batas antara kenyataan dan imajinasi bawah sadar."},
    {"q": "Apa itu modulation dalam komposisi musik?", "a": "Modulation adalah perpindahan dari satu key (tangga nada) ke key lain dalam sebuah komposisi. Ini menambah variasi dan interest harmonik, mencegah musik terdengar monoton. Modulation bisa halus (melalui pivot chord) atau dramatis (direct modulation). Composer menggunakan modulation untuk menciptakan development dan climax.", "cot": "Modulation memberi dinamika tonal dan mempertahankan interest harmonik."},
    {"q": "Apa yang dimaksud dengan seni nouveau (Art Nouveau)?", "a": "Art Nouveau adalah gaya seni dekoratif dan arsitektur populer sekitar 1890-1910 yang menekankan garis-garis organik, kurva flowing, dan motif alam seperti tanaman dan bunga. StyleArt Nouveau terlihat dalam arsitektur, furniture, poster, dan perhiasan. Alphonse Mucha terkenal dengan poster Art Nouveau yang elegan.", "cot": "Art Nouveau merayakan keindahan organik alam dalam desain dekoratif."},
    {"q": "Jelaskan apa itu fugue dalam musik klasik?", "a": "Fugue adalah bentuk komposisi kontrapuntal kompleks di mana tema (subject) diperkenalkan dan kemudian dikembangkan melalui berbagai voice dengan teknik seperti inversion, augmentation, dan stretto. Bach's The Well-Tempered Clavier berisi fugue masterpieces. Fugue menunjukkan keahlian komposer dalam kontrapung.", "cot": "Fugue adalah puncak kompleksitas kontrapuntal dalam komposisi musik."},
    {"q": "Apa itu seni fotografi fine art dan bagaimana bedanya dengan fotografi komersial?", "a": "Fotografi fine art adalah fotografi sebagai ekspresi artistik di mana fotografer mengkomunikasikan visi dan emosi personal, sering dipamerkan di galeri. Fotografi komersial bertujuan menjual produk atau jasa dengan brief dari klien. Fine art photography fokus pada konsep dan estetika, sementara komersial fokus pada kebutuhan bisnis.", "cot": "Fine art photography memprioritaskan ekspresi artistik di atas fungsi komersial."},
    {"q": "Apa yang dimaksud dengan articulation dalam permainan musik?", "a": "Articulation adalah cara not dimainkan - apakah legato (smooth dan connected), staccato (short dan detached), marcato (accented), atau tenuto (held). Articulation menambah nuansa ekspresif dan karakter pada musik. Pemilihan articulation yang tepat sangat penting untuk interpretasi yang musikal dan komunikatif.", "cot": "Articulation memberikan karakter dan ekspresi pada setiap not musik."},
    {"q": "Jelaskan apa itu impresionisme dalam seni lukis?", "a": "Impresionisme adalah gerakan seni abad ke-19 yang fokus pada menangkap kesan cahaya dan warna dalam momen tertentu, bukan detail realistis. Pelukis seperti Claude Monet, Pierre-Auguste Renoir, dan Edgar Degas melukis en plein air (outdoor) dengan brushstroke pendek dan warna cerah. Impresionisme mengubah cara seniman melihat dan merepresentasikan dunia.", "cot": "Impresionisme menangkap ephemeral quality cahaya dan atmosfer."},
    {"q": "Apa itu sonata form dalam musik klasik?", "a": "Sonata form adalah struktur komposisi tiga bagian: Exposition (memperkenalkan dua tema kontras), Development (mengembangkan tema), dan Recapitulation (mengulangi tema dengan modifikasi). Form ini banyak digunakan dalam simfoni, sonata, dan chamber music era Klasik dan Romantik, terutama oleh Mozart, Beethoven, dan Haydn.", "cot": "Sonata form adalah blueprint struktural fundamental dalam musik klasik."},
    {"q": "Apa yang dimaksud dengan seni street art dan perbedaannya dengan graffiti?", "a": "Street art adalah seni visual dibuat di ruang publik, termasuk mural, stencil, dan instalasi, sering dengan pesan sosial atau politik. Graffiti adalah subset street art yang fokus pada tulisan dan tags. Street art sering commissioned dan legal, sementara graffiti tradisional lebih underground. Banksy adalah street artist paling terkenal.", "cot": "Street art mengubah ruang urban menjadi galeri publik dengan pesan sosial."},
    {"q": "Jelaskan apa itu leitmotif dalam komposisi musik?", "a": "Leitmotif adalah tema musik berulang yang diasosiasikan dengan karakter, tempat, ide, atau emosi tertentu. Richard Wagner menggunakan leitmotif ekstensif dalam opera-operanya. John Williams menggunakan leitmotif dalam film score seperti tema Darth Vader. Leitmotif membantu penonton mengidentifikasi dan mengingat elemen naratif.", "cot": "Leitmotif adalah signature musik yang membangun koneksi emosional dan naratif."},
    {"q": "Apa itu seni dada dan mengapa dianggap revolusioner?", "a": "Dada adalah gerakan anti-seni yang muncul selama Perang Dunia I sebagai protes terhadap rasionalitas yang dianggap menyebabkan perang. Dadais menolak konvensi estetika tradisional dengan karya absurd dan provocative. Marcel Duchamp's readymades (objek sehari-hari sebagai seni) menantang definisi fundamental tentang apa itu seni.", "cot": "Dada menantang semua asumsi tentang seni dan makna artistik."},
    {"q": "Apa yang dimaksud dengan transposition dalam musik?", "a": "Transposition adalah memindahkan seluruh piece musik ke key yang berbeda dengan mempertahankan interval relatif antar not. Ini berguna untuk menyesuaikan musik dengan range vokal tertentu atau instrumen transposing. Transposition mempertahankan karakter melodi dan harmoni meski pitch absolutnya berubah.", "cot": "Transposition adalah shifting pitch tanpa mengubah struktur musik fundamental."},
    {"q": "Jelaskan apa itu seni fauvisme dan ciri-cirinya?", "a": "Fauvisme adalah gerakan seni awal abad ke-20 yang ditandai dengan penggunaan warna intens dan wild yang tidak naturalistik. Henri Matisse dan André Derain adalah tokoh utama. Nama 'Fauves' (beasts) diberikan kritikus karena penggunaan warna yang berani dan emosional. Fauvisme mengutamakan ekspresi emosi melalui warna.", "cot": "Fauvisme membebaskan warna dari representasi realistik untuk ekspresi emosional."},
    {"q": "Apa itu ornamentasi dalam musik barok?", "a": "Ornamentasi adalah dekorasi musik yang ditambahkan pada melodi dasar, seperti trill, mordent, turn, dan appoggiatura. Sangat umum di era Barok, ornamen menambah ekspresivitas dan virtuosity. Beberapa ornamen ditulis, beberapa diimprovisasi oleh pemain. Ornamentasi adalah tanda gaya dan keahlian dalam musik historis.", "cot": "Ornamentasi menghiasi melodi dengan flourishes dekoratif dan ekspresif."},
    {"q": "Apa yang dimaksud dengan seni op art?", "a": "Op art (optical art) adalah gaya seni yang menggunakan ilusi optik untuk menciptakan gerakan, vibration, atau efek 3D. Bridget Riley dan Victor Vasarely adalah tokoh op art. Karya op art menggunakan pattern geometris, kontras warna, dan perspektif untuk menipu mata dan menciptakan pengalaman visual yang dinamis.", "cot": "Op art memanipulasi persepsi visual untuk menciptakan ilusi gerakan."},
    {"q": "Jelaskan apa itu rubato dalam interpretasi musik?", "a": "Rubato adalah kebebasan ekspresif dalam tempo - memperlambat atau mempercepat secara subtle untuk ekspresi emosional. Istilah berarti 'stolen time' - waktu yang diambil di satu bagian dikembalikan di bagian lain. Rubato sangat penting dalam musik Romantik, terutama karya Chopin, untuk menciptakan interpretasi yang personal dan emosional.", "cot": "Rubato memberikan fleksibilitas temporal untuk ekspresi musik yang lebih manusiawi."},
    {"q": "Apa itu seni nouveau réalisme dan karakteristiknya?", "a": "Nouveau Réalisme adalah gerakan seni Prancis 1960an yang menggunakan objek dunia nyata (found objects) dalam karya seni. Yves Klein dengan lukisan biru monochromenya dan Arman dengan akumulasi objek adalah tokoh utama. Mirip dengan Pop Art Amerika, gerakan ini merespons konsumerisme dan budaya massa.", "cot": "Nouveau Réalisme mengintegrasikan objek real langsung ke dalam karya seni."},
    {"q": "Apa yang dimaksud dengan texture dalam komposisi musik?", "a": "Texture adalah cara berbagai voice atau layer musik berinteraksi. Ada beberapa jenis: monophonic (satu melodi), homophonic (melodi dengan accompaniment), polyphonic (banyak melodi independen), dan heterophonic (variasi simultan satu melodi). Texture memberikan dimensi pada musik - dense atau sparse, complex atau simple.", "cot": "Texture mendeskripsikan density dan interaksi vertical dalam musik."},
    {"q": "Jelaskan apa itu seni pointilisme dalam lukisan?", "a": "Pointilisme adalah teknik lukis menggunakan titik-titik kecil warna murni yang, ketika dilihat dari jarak jauh, secara optik bercampur di mata penonton. Georges Seurat dan Paul Signac adalah pionir teknik ini. Didasarkan pada teori warna ilmiah, pointilisme menciptakan luminositas dan vibrasi warna yang unik.", "cot": "Pointilisme menggunakan optical mixing untuk menciptakan warna yang luminous."},
    {"q": "Apa itu figured bass dalam musik barok?", "a": "Figured bass adalah sistem notasi di mana bass line ditulis dengan angka yang menunjukkan harmony yang harus dimainkan di atas bass tersebut. Pemain keyboard atau theorbo mengimprovisasi chordal realization. Figured bass adalah fundamental dalam musik ensemble barok dan memberikan fleksibilitas harmonik kepada pemain.", "cot": "Figured bass adalah shorthand harmonik yang memungkinkan improvisasi dalam framework."},
    {"q": "Apa yang dimaksud dengan seni assemblage?", "a": "Assemblage adalah teknik seni tiga dimensi yang menggabungkan objek-objek found atau material berbeda menjadi satu karya. Berbeda dengan collage yang dua dimensi, assemblage adalah konstruksi 3D. Joseph Cornell dengan box assemblages dan Louise Nevelson dengan wooden constructions adalah praktisi terkenal.", "cot": "Assemblage mengubah objek sehari-hari menjadi komposisi artistik 3D."},
    {"q": "Jelaskan apa itu sequence dalam komposisi musik?", "a": "Sequence adalah repetisi motif atau frase pada pitch yang berbeda (biasanya naik atau turun). Sequence menciptakan momentum, unity, dan memudahkan pendengar mengikuti perkembangan musik. Bisa diatonic (dalam satu key) atau chromatic (bermodulasi). Sequence adalah tool penting untuk development dalam komposisi.", "cot": "Sequence menggunakan repetisi transpositif untuk membangun struktur musik."},
    {"q": "Apa itu seni neo-expressionism dan kapan berkembang?", "a": "Neo-expressionism adalah gerakan seni 1970-80an yang kembali ke figurative painting dengan brushwork kasar, warna intens, dan subjek emosional atau provocative. Sebagai reaksi terhadap minimalism dan conceptual art, neo-expressionism menekankan personal expression. Georg Baselitz dan Anselm Kiefer adalah tokoh Jerman; Jean-Michel Basquiat dari Amerika.", "cot": "Neo-expressionism menghidupkan kembali ekspresi emosional direct dalam seni figuratif."},
    {"q": "Apa yang dimaksud dengan through-composed dalam bentuk musik?", "a": "Through-composed adalah bentuk komposisi di mana musik terus berkembang tanpa repetisi section besar (berbeda dengan bentuk strophic atau verse-chorus). Setiap bagian adalah baru. Common dalam art songs Jerman (Lieder) dan opera, through-composed form memungkinkan music mengikuti text atau narasi dengan fleksibilitas penuh.", "cot": "Through-composed form memprioritaskan continuous development atas repetisi struktural."},
    {"q": "Jelaskan apa itu chiaroscuro dalam seni lukis?", "a": "Chiaroscuro adalah teknik menggunakan kontras dramatis antara terang dan gelap untuk menciptakan ilusi volume dan kedalaman. Caravaggio adalah master chiaroscuro dengan pencahayaan dramatis yang teatrikal. Teknik ini menambah dimensi emosional dan fokus visual, mengarahkan mata ke elemen penting dalam komposisi.", "cot": "Chiaroscuro menggunakan light-dark contrast untuk menciptakan drama dan dimensi."},
    {"q": "Apa itu variasi dalam bentuk musik?", "a": "Variation form adalah struktur di mana tema diperkenalkan dan kemudian diulang dengan modifikasi - mengubah melodi, harmony, rhythm, texture, atau orchestration sambil mempertahankan esensi tema. Mozart's 'Twinkle Twinkle Little Star' variations dan Brahms' Variations on a Theme by Haydn adalah contoh klasik.", "cot": "Variation form mengeksplorasi kemungkinan transformatif dari tema tunggal."},
    {"q": "Apa yang dimaksud dengan seni fluxus?", "a": "Fluxus adalah gerakan seni interdisipliner 1960-70an yang mengaburkan batasan antara seni dan kehidupan sehari-hari dengan performance, events, dan publications. George Maciunas, Yoko Ono, dan Nam June Paik adalah anggota Fluxus. Gerakan ini anti-commercial, experimental, dan sering menggunakan humor dan absurditas.", "cot": "Fluxus menantang konvensi seni dengan event-based, participatory works."},
    {"q": "Jelaskan apa itu call and response dalam musik?", "a": "Call and response adalah pattern musik di mana satu frase (call) diikuti oleh frase jawaban (response), seperti percakapan musik. Sangat umum dalam musik Afrika, blues, gospel, dan jazz. Teknik ini menciptakan dialog dan interaksi, baik dalam satu instrument, antar instrumen, atau antara soloist dan ensemble.", "cot": "Call and response menciptakan struktur dialogis dan interaktif dalam musik."},
    {"q": "Apa itu seni video art dan bagaimana perkembangannya?", "a": "Video art adalah medium seni menggunakan teknologi video untuk eksplorasi artistik. Berkembang sejak 1960an dengan pioneer seperti Nam June Paik dan Bill Viola. Video art dapat berupa single-channel, multi-channel installations, atau performance documentation. Medium ini memungkinkan eksplorasi waktu, gerakan, dan narrative dengan cara yang unik.", "cot": "Video art menggunakan moving images sebagai medium untuk eksplorasi konseptual."},
    {"q": "Apa yang dimaksud dengan polyrhythm dalam musik?", "a": "Polyrhythm adalah penggunaan simultan dua atau lebih rhythm patterns berbeda yang tidak sinkron satu sama lain. Contoh umum adalah 3 against 2 atau 4 against 3. Polyrhythm sangat menonjol dalam musik Afrika, jazz, dan musik kontemporer, menciptakan kompleksitas ritmis dan interest yang kaya.", "cot": "Polyrhythm menciptakan multi-layered rhythmic complexity dan tension produktif."},
    {"q": "Jelaskan apa itu seni abstrak geometris?", "a": "Abstrak geometris menggunakan bentuk-bentuk geometris seperti lingkaran, persegi, garis, dan warna datar untuk menciptakan komposisi non-representational. Piet Mondrian dengan grid primary colors dan Kazimir Malevich dengan 'Black Square' adalah tokoh utama. Fokusnya pada pure form, balance, dan harmony visual universal.", "cot": "Abstrak geometris mereduksi seni pada elemen visual paling fundamental."},
    {"q": "Apa itu pentatonic scale dalam musik?", "a": "Pentatonic scale adalah tangga nada lima nada yang ditemukan dalam banyak tradisi musik dunia. Major pentatonic (1-2-3-5-6) dan minor pentatonic (1-♭3-4-5-♭7) sangat common. Karena menghindari semitone steps, pentatonic scale terdengar consonant dan mudah untuk improvisasi, populer dalam folk, blues, dan rock music.", "cot": "Pentatonic scale adalah universal musical structure yang inherently melodious."},
    {"q": "Apa yang dimaksud dengan seni site-specific?", "a": "Site-specific art adalah karya yang dirancang untuk lokasi tertentu dan tidak dapat dipindahkan tanpa kehilangan makna atau fungsi. Richard Serra's 'Tilted Arc' adalah contoh controversial. Karya site-specific mempertimbangkan arsitektur, sejarah, dan konteks sosial lokasi, menciptakan dialog antara art dan environment.", "cot": "Site-specific work mengintegrasikan lokasi sebagai bagian integral dari makna karya."},
    {"q": "Jelaskan apa itu augmented dan diminished intervals dalam musik?", "a": "Augmented interval adalah interval yang diperlebar satu semitone dari major atau perfect interval (contoh: augmented fifth C-G♯). Diminished interval adalah interval yang dipersempit satu semitone dari minor atau perfect interval (contoh: diminished fifth C-G♭). Interval ini menambah tension dan color harmonik yang unik dalam komposisi.", "cot": "Augmented dan diminished intervals memperluas palet harmonik dengan dissonance."},
    {"q": "Apa itu seni bio art?", "a": "Bio art adalah praktik artistik kontemporer yang menggunakan living organisms, biological materials, atau scientific processes sebagai medium. Eduardo Kac yang menciptakan fluorescent rabbit GFP Bunny adalah contoh controversial. Bio art mengeksplorasi etika, life sciences, dan hubungan antara nature dan technology.", "cot": "Bio art mengaburkan batasan antara seni, sains, dan kehidupan itu sendiri."},
    {"q": "Apa yang dimaksud dengan whole tone scale dalam musik?", "a": "Whole tone scale adalah skala enam nada di mana setiap interval adalah whole step (2 semitones). Karena tidak ada semitone dan tertiary relationships, whole tone scale terdengar ambiguous dan dreamlike. Claude Debussy menggunakan extensively untuk menciptakan atmosfer impressionistic. Scale ini menghindari traditional tonal centers.", "cot": "Whole tone scale menciptakan ambiguitas tonal yang ethereal dan mysterious."},
    {"q": "Jelaskan apa itu seni lowbrow atau pop surrealism?", "a": "Lowbrow atau pop surrealism adalah gerakan seni yang bermula dari underground comix, punk music, dan hot rod culture. Mark Ryden dan Robert Williams adalah tokoh kunci. Karya lowbrow menggabungkan surrealism dengan pop culture, cartoons, dan kitsch dengan technical skill tinggi namun subject matter yang playful atau dark.", "cot": "Lowbrow art mengangkat subculture aesthetics ke status fine art."},
    {"q": "Apa itu chromaticism dalam harmoni musik?", "a": "Chromaticism adalah penggunaan nada di luar key (nada chromatic) untuk memperkaya harmony dan melodi. Wagner menggunakan chromaticism ekstensif, menciptakan ambiguitas tonal dan tension. Chromaticism berkembang dari ornamental di era Barok ke structural di era Romantik, akhirnya mengarah pada atonality.", "cot": "Chromaticism memperluas vocabulary tonal dengan nada non-diatonic."},
    {"q": "Apa yang dimaksud dengan seni generatif?", "a": "Seni generatif adalah seni yang dibuat menggunakan sistem autonomous seperti algoritma komputer, mathematical formulas, atau processes yang semi-random. Manfred Mohr dan Casey Reas adalah praktisi generative art. Artist menetapkan rules atau parameters, sistem menghasilkan output yang sering unpredictable namun dalam framework yang ditentukan.", "cot": "Generative art menggunakan systems dan rules untuk menciptakan karya dengan variasi."},
    {"q": "Jelaskan apa itu voice leading dalam harmoni musik?", "a": "Voice leading adalah cara individual voices (parts) bergerak dari satu chord ke chord berikutnya. Good voice leading mengikuti prinsip: stepwise motion (gerak bertahap) lebih baik dari leaps, avoid parallel fifths/octaves, resolve tendency tones properly. Voice leading yang smooth menciptakan flow harmonik yang natural dan singable.", "cot": "Voice leading adalah choreography horizontal dalam progression vertikal harmony."},
    {"q": "Apa itu seni relational art?", "a": "Relational art adalah praktik seni yang fokus pada interaksi manusia dan konteks sosial sebagai karya seni itu sendiri. Curator Nicolas Bourriaud mencetuskan term ini. Rirkrit Tiravanija yang memasak dan membagi makanan di galeri adalah contoh. Relational art menekankan experience, participation, dan social engagement daripada object.", "cot": "Relational art menggeser fokus dari object ke social interactions dan experiences."},
    {"q": "Apa yang dimaksud dengan blue notes dalam musik jazz?", "a": "Blue notes adalah nada-nada yang di-flatten (diturunkan) sedikit dari major scale - terutama third, fifth, dan seventh degrees. Blue notes menciptakan karakteristik sound 'blue' yang ekspresif dan emosional dalam blues dan jazz. Micro-tuning ini menambah depth expressive yang tidak bisa dicapai dengan equal temperament standard.", "cot": "Blue notes menambah expressivity melalui pitch bending yang mikrotonik."},
    {"q": "Jelaskan apa itu seni appropriation?", "a": "Appropriation art adalah praktik menggunakan imagery atau objek yang sudah ada (sering dari mass media atau art history) dan re-contextualizing mereka dalam karya baru. Sherrie Levine memotret ulang foto Walker Evans; Cindy Sherman mengappropriate visual language film. Appropriation mempertanyakan authorship, originality, dan ownership dalam seni.", "cot": "Appropriation art menantang konsep originality dengan reclaiming existing images."},
    {"q": "Apa itu secondary dominant dalam teori harmoni?", "a": "Secondary dominant adalah dominant chord sementara yang mengarah ke chord selain tonic. Contoh: V/V (dominant of dominant) atau V/vi. Secondary dominants memperkaya progression harmonik dengan tonicization sementara, menambah color dan forward motion tanpa modulation penuh. Sangat common dalam musik klasik dan jazz.", "cot": "Secondary dominants memperluas functionality tonal dengan temporary tonicizations."},
    {"q": "Apa yang dimaksud dengan seni outsider art?", "a": "Outsider art adalah karya yang dibuat oleh self-taught artists di luar mainstream art world, sering oleh individu dengan mental illness atau yang terisolasi dari society. Henry Darger dan Adolf Wölfli adalah contoh. Outsider art dihargai untuk authenticity, personal vision yang intense, dan freedom dari konvensi artistik.", "cot": "Outsider art menawarkan perspektif unik dari luar establishment seni formal."},
    {"q": "Jelaskan apa itu pedal point atau pedal tone dalam musik?", "a": "Pedal point adalah nada yang sustained (biasanya di bass) sementara harmony berubah di atasnya. Sering menggunakan tonic atau dominant, pedal point menciptakan tension dan anticipation, terutama saat harmony bergerak ke chords yang dissonant dengan pedal. Common di bagian climactic dan menjelang cadence.", "cot": "Pedal point menciptakan harmonic tension dengan sustaining single pitch."},
    {"q": "Apa itu seni participatory atau socially engaged art?", "a": "Participatory art melibatkan audiens sebagai co-creators atau participants aktif daripada passive observers. Theaster Gates yang revitalisasi neighborhoods melalui art projects dan Tania Bruguera dengan political performances adalah contoh. Art ini fokus pada social impact, community building, dan democratizing artistic production.", "cot": "Participatory art mengaktifkan audiens sebagai collaborators dalam artistic process."},
    {"q": "Apa yang dimaksud dengan phrase dalam struktur musik?", "a": "Phrase adalah unit musik yang lengkap, seperti kalimat dalam bahasa. Biasanya 4 atau 8 bar, phrase memiliki beginning, middle, dan end dengan cadence. Phrase dapat berupa question-answer pairs (antecedent-consequent). Phrasing yang baik dalam performance memberikan shape dan meaning pada melodi.", "cot": "Phrase adalah building block naratif yang memberi struktur dan breath musik."},
    {"q": "Jelaskan apa itu seni glitch art?", "a": "Glitch art adalah praktik menggunakan digital atau analog errors - corruption, artifacts, distortions - sebagai aesthetic material. Rosa Menkman dan Nam June Paik (video glitches) adalah praktisi. Glitch art merayakan malfunction dan unpredictability teknologi, menantang perfection dan questioning relationship antara humans dan machines.", "cot": "Glitch art  transforms technological failures menjadi aesthetic statements."},
    {"q": "Apa itu borrowed chord atau modal interchange dalam harmoni?", "a": "Borrowed chord adalah chord yang diambil dari parallel key (major meminjam dari minor atau sebaliknya). Contoh: dalam C major, menggunakan iv dari C minor. Modal interchange memperkaya palet harmonik dan menambah color emosional tanpa modulation penuh. Beatles sering menggunakan borrowed chords untuk distinctive sound.", "cot": "Borrowed chords memperluas options harmonik dengan mixing parallel major/minor."},
    {"q": "Apa yang dimaksud dengan seni acoustic atau sound art?", "a": "Sound art adalah praktik artistik yang fokus pada sound sebagai medium utama - berbeda dari musik yang fokus pada structure dan melody. Bill Fontana dengan environmental sound sculptures dan Janet Cardiff dengan audio walks adalah contoh. Sound art mengeksplorasi spatial, temporal, dan experiential properties of sound.", "cot": "Sound art menggunakan auditory experience sebagai primary artistic material."},
    {"q": "Jelaskan apa itu Neapolitan sixth chord dalam musik?", "a": "Neapolitan sixth chord (♭II6 atau N6) adalah major triad built pada flattened second degree dari scale, biasanya dalam first inversion. Sangat ekspresif dan dramatic, sering digunakan menjelang cadence untuk heightened emotion. Common dalam musik klasik dan romantik, terutama dalam minor keys.", "cot": "Neapolitan chord menambah dramatic intensity dengan altered supertonic harmony."},
    {"q": "Apa itu seni new media dan teknologi yang digunakan?", "a": "New media art menggunakan teknologi digital dan electronic emerging sebagai medium - internet, VR, AR, AI, interactivity, software. Rafael Lozano-Hemmer dengan interactive installations dan teamLab dengan digital immersive environments adalah contoh. New media art terus evolve dengan teknologi baru.", "cot": "New media art memanfaatkan cutting-edge technology untuk eksplorasi artistik."},
    {"q": "Apa yang dimaksud dengan enharmonic equivalence dalam musik?", "a": "Enharmonic equivalence adalah ketika dua nada terdengar sama tetapi ditulis berbeda - seperti C♯ dan D♭, atau F♯ dan G♭. Meski identical dalam equal temperament, context harmonik menentukan spelling yang correct. Enharmonic modulation menggunakan ambiguitas ini untuk pivot ke key yang distant secara elegant.", "cot": "Enharmonic equivalence memungkinkan flexibility notasi dan modulation harmonic."},
    {"q": "Jelaskan apa itu seni post-internet?", "a": "Post-internet art adalah seni yang dibuat di era di mana internet sudah pervasive dan mempengaruhi semua aspek kehidupan. Tidak harus digital - bisa physical objects yang reflect internet culture. Amalia Ulman dan Jon Rafman adalah praktisi. Post-internet art mengeksplorasi bagaimana internet shapes identity, culture, dan perception.", "cot": "Post-internet art reflects kondisi hidup dalam dunia yang fully networked."},
    {"q": "Apa itu augmented sixth chords dalam harmoni?", "a": "Augmented sixth chords adalah pre-dominant chords dengan karakteristik augmented sixth interval, leading strongly ke dominant. Tiga types: Italian (It+6), French (Fr+6), dan German (Ger+6), berbeda dalam additional notes. Sangat chromatic dan dramatic, common dalam musik Romantik untuk heightened harmonic tension.", "cot": "Augmented sixth chords menciptakan powerful pull ke dominant melalui chromatic voice leading."},
    {"q": "Apa yang dimaksud dengan seni eco-art atau environmental art?", "a": "Eco-art adalah seni yang addresses environmental issues dan promotes ecological awareness. Andy Goldsworthy dengan ephemeral natural sculptures, Agnes Denes menanam wheat field di Manhattan adalah contoh. Eco-art dapat berupa land reclamation, activism, education, atau poetic meditations on nature dan sustainability.", "cot": "Eco-art menggunakan artistic practice untuk environmental advocacy dan awareness."},
]

print(f"Generated {len(musik_seni_new)} Q&A pairs for musik_seni.json")

# Continue with loading and updating the file
filepath = 'dataset_topics/musik_seni.json'
data = load_json(filepath)
original_count = len(data)
data.extend(musik_seni_new)
save_json(filepath, data)

print(f"\n✓ Updated {filepath}")
print(f"  Original count: {original_count}")
print(f"  New count: {len(data)}")
print(f"  Added: {len(musik_seni_new)} entries")
print("\nSample of 3 new QA pairs:")
for i, qa in enumerate(musik_seni_new[:3], 1):
    print(f"\n{i}. Q: {qa['q']}")
    print(f"   A: {qa['a'][:100]}...")

EOF
